version: '3.9'
services:
  coupon-service:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: npm run start:dev
    depends_on:
      - postgres
      - mongo
      - redis

    # seeder:
    #   build:
    #     context: .
    #   command: npm run seed:special-offers
    #   depends_on:
    #     - postgres
    #   environment:
    #     - DATABASE_URL=postgres://postgres:postgres@postgres:5432/coupondb

  postgres:
    image: 'postgres:14'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: voucherdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  mongo:
    image: 'mongo:5'
    restart: always
    volumes:
      - mongodata:/data/db
    ports:
      - '27017:27017'

  redis:
    image: 'redis:7'
    restart: always
    ports:
      - '6379:6379'

volumes:
  pgdata:
  mongodata: